version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nishantdev
      MYSQL_DATABASE: ohnomovies
      MYSQL_USER: nishantdev
      MYSQL_PASSWORD: nishantdev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticket-net

volumes:
  mysql_data:

networks:
  ticket-net:
    driver: bridge
